server:
  port: 8089
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8
    username: root
#    - 对称加密 aes
#    - 非对称加密 rsa
#    password: e@8y-eEG
    password: ${DATASOURCE_PWD:E0TDiIDmRKCz5lymk2RKfFPvvPYGQJBgbMqRf+DWk0qjMfcCZRhGp6FhwS1X5GICiTPa3E9W4DaTQARmhUhC4A==}

  redis:
    host: 127.0.0.1
    port: 6379
    database: 2
#    password: 63061323



#mybatis:
#  type-aliases-package: com.demo1.Entity
#  mapper-locations: classpath:/mybatis/*.xml
#
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

