server:
  port: 8089
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8
    username: root
#    TODO 密码加密
#    - 对称加密 aes
#    - 非对称加密 rsa
#    password: e@8y-eEG
    password: ${DATASOURCE_PWD:a+aPogpLo7uN+739jYOmK6IrRnr9mocuRuqIUaMAPcR5Ug6n1anW6gD5U/Aa+SUBjEhLmbeNjU5tGyXXGXkwsg==}
    publickey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAIfjZNWzwR4fszkcRpldTIb0Od8XrMUmlY1RlgQui/1GhNN1fue87jBB+lLGMqmkja5fxYrBBYK0EgAbdkbkJBcCAwEAAQ==
    druid:
        filter:
          config:
            enabled: true
        connection-properties: config.decrypt=true;config.decrypt.key=${spring.datasource.publickey}





#mybatis:
#  type-aliases-package: com.demo1.Entity
#  mapper-locations: classpath:/mybatis/*.xml
#
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

