server:
  port: 8089
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8
    username: root
#    TODO 密码加密
#    - 对称加密 aes
#    - 非对称加密 rsa
#    password: e@8y-eEG
    password: J07fdnirJdZc4/13+okB4rhCViwa/3ZcMMNwWj/A+GXi9aCLVHNuP0eOKhae1AEJcG1p1rPmhp/YohbrVOPp4Q==
#    publickey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAIp8hWcaqTrV6JvVh11/o8DquocMnVbsYSGkfiAe3FGPc6gqdYx5tuMXE1phJ2kTXo/rHQik/TJBm3IvqICv4xECAwEAAQ==
    druid:
      filters:
          config:
            enabled: true
      connection-properties: config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJueHgDm3/26IkBASdby5Y0zSI/AnBMVi57pflq01jQjXXzmwJEkmRHU4s9Fm19m6RiJz0645R7+CY4ROrZejCECAwEAAQ==





#mybatis:
#  type-aliases-package: com.demo1.Entity
#  mapper-locations: classpath:/mybatis/*.xml
#
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

